# Generated by Django 3.0.5 on 2020-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='linked', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=300),
        ),
    ]
